import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useCommercialData } from '@/app/providers/commercialDataContext'
import { useInsightStatus } from '@/app/providers/insightStatusContext'
import { useReadyWorkspace } from '@/app/providers/workspaceContext'
import { computeCommercialMetrics } from '@/domain/metrics/dashboardMetrics'
import { resolvePeriod } from '@/domain/metrics/periods'
import type { Insight } from '@/domain/intelligence/types'
import { HealthIndicator } from '@/features/dashboard/components/HealthIndicator'
import { IntelligenceFeed } from './components/IntelligenceFeed'
import {
  EMPTY_INTELLIGENCE_FILTERS,
  IntelligenceFilters,
  type IntelligenceFilterState,
} from './components/IntelligenceFilters'
import { IntelligenceOverviewStrip } from './components/IntelligenceOverview'
import { InsightDetailPanel } from './components/InsightDetailPanel'
import { InsightList } from './components/InsightList'
import { RevenueAtRiskPanel } from './components/RevenueAtRiskPanel'
import { TodaysFocus } from './components/TodaysFocus'
import { useIntelligence } from './useIntelligence'

/**
 * Commercial Intelligence.
 *
 * The reading order is the answer to one question: what needs my attention now.
 * Health and the overview first, then the few things to act on, then everything
 * else the engine found, with the exposure and the timeline behind it.
 */
export function IntelligencePage() {
  const workspace = useReadyWorkspace()
  const { dataset, customerById, ownerById } = useCommercialData()
  const { setStatus, reopen } = useInsightStatus()
  const navigate = useNavigate()

  const now = useMemo(() => new Date(), [])
  const [filters, setFilters] = useState<IntelligenceFilterState>(
    EMPTY_INTELLIGENCE_FILTERS,
  )
  const [selected, setSelected] = useState<Insight | null>(null)

  const period = useMemo(() => resolvePeriod(filters.period, now), [filters.period, now])
  const metrics = useMemo(
    () => computeCommercialMetrics(dataset, workspace, period, null),
    [dataset, workspace, period],
  )

  const intelligence = useIntelligence(metrics, now)

  const filtered = useMemo(() => {
    const term = filters.search.trim().toLowerCase()

    return intelligence.insights.filter((insight) => {
      if (filters.severity !== 'all' && insight.severity !== filters.severity) return false
      if (filters.kind !== 'all' && insight.type !== filters.kind) return false
      if (filters.category !== 'all' && insight.category !== filters.category) return false

      if (filters.status === 'unresolved') {
        if (insight.status === 'resolved' || insight.status === 'dismissed') return false
      } else if (filters.status !== 'all' && insight.status !== filters.status) {
        return false
      }

      if (term) {
        const haystack = [
          insight.title,
          insight.description,
          insight.entityName ?? '',
          insight.reason,
        ]
          .join(' ')
          .toLowerCase()
        if (!haystack.includes(term)) return false
      }

      return true
    })
  }, [intelligence.insights, filters])

  // Today's Focus takes the highest-priority live signals, whatever the list
  // filters happen to be: it answers "what now", not "what did I filter to".
  const focus = useMemo(
    () =>
      intelligence.insights
        .filter(
          (insight) =>
            insight.status !== 'resolved' &&
            insight.status !== 'dismissed' &&
            insight.severity !== 'low',
        )
        .slice(0, 5),
    [intelligence.insights],
  )

  const criticalAlerts = useMemo(
    () =>
      filtered.filter(
        (insight) => insight.severity === 'critical' || insight.severity === 'high',
      ),
    [filtered],
  )

  const positives = useMemo(
    () => filtered.filter((insight) => insight.severity === 'positive'),
    [filtered],
  )

  const others = useMemo(
    () =>
      filtered.filter(
        (insight) =>
          insight.severity === 'medium' || insight.severity === 'low',
      ),
    [filtered],
  )

  return (
    <div className="animate-rise space-y-7">
      <header className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0 space-y-2">
          <h1 className="text-page font-semibold text-ink">
            Commercial Intelligence
          </h1>
          <p className="text-sm text-ink-muted">
            What requires your attention right now, and why.
          </p>
          <p className="pt-1 text-xs text-ink-faint">
            Every signal below is produced by a fixed set of rules over your own
            commercial data. Nothing is generated by a model.
          </p>
        </div>
        <HealthIndicator health={intelligence.health} className="shrink-0" />
      </header>

      <IntelligenceOverviewStrip overview={intelligence.overview} />

      <TodaysFocus insights={focus} onOpen={setSelected} />

      <IntelligenceFilters
        filters={filters}
        onChange={setFilters}
        onClear={() =>
          setFilters((current) => ({
            ...EMPTY_INTELLIGENCE_FILTERS,
            period: current.period,
          }))
        }
      />

      <InsightList
        title="Critical Alerts"
        description="Signals that could materially affect revenue if nothing changes."
        insights={criticalAlerts}
        onOpen={setSelected}
        onStatus={setStatus}
        onReopen={reopen}
        emptyTitle="Everything looks healthy"
        emptyDescription="No critical or high-priority signal matches the current filters."
      />

      <RevenueAtRiskPanel
        report={intelligence.revenueAtRisk}
        ownerName={(id) => ownerById(id)?.name ?? 'Unassigned'}
        customerName={(id) => customerById(id)?.name ?? 'Unknown account'}
        onOpenOpportunity={() => navigate('/pipeline')}
      />

      <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <InsightList
          title="Opportunities & Positive Signals"
          description="Conditions worth protecting or repeating."
          insights={positives}
          onOpen={setSelected}
          onStatus={setStatus}
          onReopen={reopen}
          emptyTitle="No strong positive signals detected yet"
          emptyDescription="No rule found a condition worth calling out in this selection."
        />

        <InsightList
          title="Everything Else"
          description="Lower-priority signals, kept out of the way but not hidden."
          insights={others}
          onOpen={setSelected}
          onStatus={setStatus}
          onReopen={reopen}
          emptyTitle="Nothing else to report"
          emptyDescription="No medium or low-priority signal matches the current filters."
        />
      </div>

      {intelligence.anomaliesUnavailable ? (
        <p className="rounded-panel border border-dashed border-line px-5 py-4 text-xs leading-relaxed text-ink-faint">
          Not enough historical data to detect meaningful anomalies yet. Anomaly rules need
          at least three completed months of commercial history before they will report
          anything, and this workspace has {intelligence.baseline.months}.
        </p>
      ) : null}

      <IntelligenceFeed insights={filtered} onOpen={setSelected} />

      <InsightDetailPanel
        insight={selected}
        onClose={() => setSelected(null)}
        onStatus={(id, status) => {
          setStatus(id, status)
          setSelected(null)
        }}
        onReopen={(id) => {
          reopen(id)
          setSelected(null)
        }}
      />
    </div>
  )
}
